### ISSUE TITLE
Сделать на странице /all pagination

### ISSUE THREAD

**Issue by tatiana-rosary** [blackisnotcool/mp-dev#3]
заодно сделать проверку /all?page=100 (большое число), с сервера возвращается последняя страница. Нужно корректно обработать такой запрос на клиенте. Можно не выделять текущую страницу в таком запросе.

**Comment by blackisnotcool** [comment]
bac21343583a7f6bfda001942732d3466119c4b4

**Comment by blackisnotcool** [comment]
a9754bf056e7a4b6f0a8907c9451eb2f6ea602fc
